# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  shift_pro_app_nginx:
    restart: always
    build:
      context: ./client
    ports:
    - "3000:80"
    depends_on:
    - shift_pro_server

  shift_pro_mysql:
    container_name: shiftpro_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: shiftpro
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  shift_pro_server:
    restart: always
    build:
      context: ./server
    volumes:
    - ./server:/server
    - ~/.m2:/root/.m2
    ports:
    - "8080:8080"
    depends_on:
    - shift_pro_mysql
